"""initial_schema

Revision ID: df2c477aaabb
Revises: 
Create Date: 2026-09-12 14:52:25.299400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'df2c477aaabb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Ensure vector extension is present
    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the user'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='User email address — primary login identifier'),
    sa.Column('full_name', sa.String(length=255), nullable=True, comment='Display name'),
    sa.Column('organization', sa.String(length=255), nullable=True, comment="User's organization or company name"),
    sa.Column('role', sa.String(length=50), nullable=False, comment='User role: admin | procurement_lead | legal | viewer'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Soft-delete flag — inactive users cannot log in'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last-updated timestamp'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('contracts',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the contract'),
    sa.Column('uploaded_by', sa.UUID(), nullable=True, comment='User who uploaded this contract'),
    sa.Column('title', sa.String(length=500), nullable=False, comment='Contract title or document name'),
    sa.Column('vendor', sa.String(length=255), nullable=True, comment='Counterparty / vendor name'),
    sa.Column('contract_type', sa.String(length=100), nullable=True, comment='Contract type: MSA | NDA | SaaS | PSA | Lease | Employment | Other'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='Contract lifecycle status: active | expired | pending_review | terminated'),
    sa.Column('effective_date', sa.Date(), nullable=True, comment='Date the contract became effective'),
    sa.Column('expiry_date', sa.Date(), nullable=True, comment='Date the contract expires or auto-renews'),
    sa.Column('contract_value', sa.Numeric(precision=18, scale=2), nullable=True, comment='Total contract value in USD (or base currency)'),
    sa.Column('currency', sa.String(length=10), nullable=False, comment='Currency code for contract_value (ISO 4217)'),
    sa.Column('file_name', sa.String(length=500), nullable=True, comment='Original uploaded filename'),
    sa.Column('file_storage_key', sa.String(length=1000), nullable=True, comment='Storage path or object-key for the original PDF file'),
    sa.Column('page_count', sa.Integer(), nullable=True, comment='Total page count of the contract document'),
    sa.Column('processing_status', sa.String(length=50), nullable=False, comment='Ingestion pipeline state: pending | extracting | chunking | embedding | indexing | ready | failed'),
    sa.Column('processing_error', sa.Text(), nullable=True, comment='Non-sensitive error description if processing failed'),
    sa.Column('risk_level', sa.String(length=20), nullable=True, comment='Aggregate risk level: critical | high | medium | low | none'),
    sa.Column('has_auto_renewal', sa.Boolean(), nullable=True, comment='Extracted: whether the contract has an auto-renewal clause'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last-updated timestamp'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contracts_contract_type'), 'contracts', ['contract_type'], unique=False)
    op.create_index(op.f('ix_contracts_expiry_date'), 'contracts', ['expiry_date'], unique=False)
    op.create_index(op.f('ix_contracts_processing_status'), 'contracts', ['processing_status'], unique=False)
    op.create_index(op.f('ix_contracts_risk_level'), 'contracts', ['risk_level'], unique=False)
    op.create_index(op.f('ix_contracts_status'), 'contracts', ['status'], unique=False)
    op.create_index(op.f('ix_contracts_uploaded_by'), 'contracts', ['uploaded_by'], unique=False)
    op.create_index(op.f('ix_contracts_vendor'), 'contracts', ['vendor'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for this audit event'),
    sa.Column('user_id', sa.UUID(), nullable=True, comment='User who performed this action. NULL for system-initiated events.'),
    sa.Column('actor', sa.String(length=255), nullable=False, comment="Human-readable actor identifier. Either user email/name or 'system' for automated events."),
    sa.Column('event_type', sa.String(length=100), nullable=False, comment='Stable dot-notation event code. Example: contract.uploaded, risk_signal.acknowledged, user.login'),
    sa.Column('entity_type', sa.String(length=50), nullable=True, comment='Type of entity acted upon: contract | clause | obligation | risk_signal | user'),
    sa.Column('entity_id', sa.String(length=255), nullable=True, comment='UUID (as string) of the entity acted upon'),
    sa.Column('contract_id', sa.UUID(), nullable=True, comment='Contract associated with this event, if applicable'),
    sa.Column('details', sa.Text(), nullable=True, comment='JSON-encoded supplementary data about the event. Must not contain passwords or full credentials.'),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='Client IP address at the time of the event (Phase 6+)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Event timestamp — immutable after insert'),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_contract_id'), 'audit_events', ['contract_id'], unique=False)
    op.create_index(op.f('ix_audit_events_created_at'), 'audit_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_events_entity_type'), 'audit_events', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_events_event_type'), 'audit_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_events_user_id'), 'audit_events', ['user_id'], unique=False)
    op.create_table('document_chunks',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for this chunk'),
    sa.Column('contract_id', sa.UUID(), nullable=False, comment='Parent contract this chunk belongs to'),
    sa.Column('page_number', sa.Integer(), nullable=False, comment='1-indexed page number in the source PDF where this chunk appears'),
    sa.Column('chunk_index', sa.Integer(), nullable=False, comment='0-indexed position of this chunk within the page'),
    sa.Column('char_start', sa.Integer(), nullable=True, comment='Character offset (start) of this chunk within the full extracted page text'),
    sa.Column('char_end', sa.Integer(), nullable=True, comment='Character offset (end) of this chunk within the full extracted page text'),
    sa.Column('section_header', sa.String(length=500), nullable=True, comment="Nearest document section heading above this chunk (e.g. '7. Termination')"),
    sa.Column('text', sa.Text(), nullable=False, comment='Raw text content of this chunk'),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(), nullable=True, comment='Dense vector embedding of chunk text. Populated in Phase 2. Dimension TBD pending DEC-010.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_chunks_contract_id'), 'document_chunks', ['contract_id'], unique=False)
    op.create_table('clauses',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for this clause'),
    sa.Column('contract_id', sa.UUID(), nullable=False, comment='Parent contract this clause belongs to'),
    sa.Column('source_chunk_id', sa.UUID(), nullable=True, comment='Source document chunk from which this clause was extracted'),
    sa.Column('clause_type', sa.String(length=100), nullable=False, comment='Legal clause type: termination | liability | indemnification | auto_renewal | payment | confidentiality | governing_law | dispute_resolution | other'),
    sa.Column('clause_label', sa.String(length=255), nullable=True, comment="Human-readable clause label (e.g., 'Section 7.2 — Early Termination')"),
    sa.Column('verbatim_text', sa.Text(), nullable=False, comment='Exact verbatim text of the clause as it appears in the contract'),
    sa.Column('page_number', sa.Integer(), nullable=True, comment='Page number in the source PDF where this clause appears (1-indexed)'),
    sa.Column('extracted_facts', sa.Text(), nullable=True, comment='JSON object of structured facts extracted from this clause by the LLM. Example: {"notice_period_days": 15, "auto_renewal": true}. Populated in Phase 4.'),
    sa.Column('extraction_confidence', sa.Float(), nullable=True, comment='LLM extraction confidence score (0.0 to 1.0). Populated in Phase 4.'),
    sa.Column('is_reviewed', sa.Boolean(), nullable=False, comment='Whether a human reviewer has verified this clause extraction'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last-updated timestamp'),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_chunk_id'], ['document_chunks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clauses_clause_type'), 'clauses', ['clause_type'], unique=False)
    op.create_index(op.f('ix_clauses_contract_id'), 'clauses', ['contract_id'], unique=False)
    op.create_index(op.f('ix_clauses_source_chunk_id'), 'clauses', ['source_chunk_id'], unique=False)
    op.create_table('obligations',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for this obligation'),
    sa.Column('contract_id', sa.UUID(), nullable=False, comment='Parent contract this obligation belongs to'),
    sa.Column('source_clause_id', sa.UUID(), nullable=True, comment='Source clause from which this obligation was extracted'),
    sa.Column('source_chunk_id', sa.UUID(), nullable=True, comment='Source document chunk for direct evidence reference'),
    sa.Column('title', sa.String(length=500), nullable=False, comment='Short title or description of the obligation'),
    sa.Column('description', sa.Text(), nullable=True, comment='Full obligation description extracted from the contract'),
    sa.Column('verbatim_evidence', sa.Text(), nullable=True, comment='Exact quoted text from the contract supporting this obligation'),
    sa.Column('page_number', sa.Integer(), nullable=True, comment='Page number in the source PDF where the obligation appears (1-indexed)'),
    sa.Column('responsible_party', sa.String(length=255), nullable=True, comment="Entity responsible for fulfilling this obligation (e.g., 'Vendor', 'Customer')"),
    sa.Column('due_date', sa.Date(), nullable=True, comment='Specific due date for the obligation, if defined'),
    sa.Column('frequency', sa.String(length=100), nullable=True, comment="Recurrence frequency for ongoing obligations (e.g., 'Monthly', 'Annually', 'On-demand')"),
    sa.Column('is_recurring', sa.Boolean(), nullable=False, comment='Whether this is a recurring obligation'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='Tracking status: pending | in_progress | completed | overdue | waived'),
    sa.Column('priority', sa.String(length=20), nullable=False, comment='Priority level: high | medium | low'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last-updated timestamp'),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_chunk_id'], ['document_chunks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_clause_id'], ['clauses.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_obligations_contract_id'), 'obligations', ['contract_id'], unique=False)
    op.create_index(op.f('ix_obligations_due_date'), 'obligations', ['due_date'], unique=False)
    op.create_index(op.f('ix_obligations_priority'), 'obligations', ['priority'], unique=False)
    op.create_index(op.f('ix_obligations_source_chunk_id'), 'obligations', ['source_chunk_id'], unique=False)
    op.create_index(op.f('ix_obligations_source_clause_id'), 'obligations', ['source_clause_id'], unique=False)
    op.create_index(op.f('ix_obligations_status'), 'obligations', ['status'], unique=False)
    op.create_table('risk_signals',
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for this risk signal'),
    sa.Column('contract_id', sa.UUID(), nullable=False, comment='Parent contract this risk signal belongs to'),
    sa.Column('source_clause_id', sa.UUID(), nullable=True, comment='Source clause that triggered this risk signal'),
    sa.Column('source_chunk_id', sa.UUID(), nullable=True, comment='Source document chunk for direct evidence reference'),
    sa.Column('severity', sa.String(length=20), nullable=False, comment='Risk severity: critical | high | medium | low'),
    sa.Column('category', sa.String(length=100), nullable=True, comment='Risk category: termination | liability | renewal | indemnification | payment | confidentiality | compliance | other'),
    sa.Column('rule_id', sa.String(length=100), nullable=False, comment='Stable identifier for the business rule that fired. Example: RULE_NOTICE_PERIOD_SHORT, RULE_AUTO_RENEWAL_IMMINENT, RULE_UNCAPPED_LIABILITY'),
    sa.Column('rule_description', sa.String(length=500), nullable=False, comment='Human-readable description of the triggered rule'),
    sa.Column('triggered_fact', sa.String(length=500), nullable=True, comment="The specific extracted fact that triggered this rule. Example: 'notice_period_days: 15'"),
    sa.Column('title', sa.String(length=500), nullable=False, comment='Short risk signal title displayed in the UI'),
    sa.Column('verbatim_evidence', sa.Text(), nullable=True, comment='Exact quoted text from the contract that supports this risk signal'),
    sa.Column('page_number', sa.Integer(), nullable=True, comment='Page number in the source PDF where the risk evidence appears (1-indexed)'),
    sa.Column('recommended_action', sa.Text(), nullable=True, comment='Plain-English recommended action for the procurement / legal team'),
    sa.Column('is_acknowledged', sa.Boolean(), nullable=False, comment='Whether this risk has been acknowledged by a reviewer'),
    sa.Column('is_false_positive', sa.Boolean(), nullable=False, comment='Whether this signal has been marked as a false positive by a reviewer'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last-updated timestamp'),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_chunk_id'], ['document_chunks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_clause_id'], ['clauses.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_signals_category'), 'risk_signals', ['category'], unique=False)
    op.create_index(op.f('ix_risk_signals_contract_id'), 'risk_signals', ['contract_id'], unique=False)
    op.create_index(op.f('ix_risk_signals_rule_id'), 'risk_signals', ['rule_id'], unique=False)
    op.create_index(op.f('ix_risk_signals_severity'), 'risk_signals', ['severity'], unique=False)
    op.create_index(op.f('ix_risk_signals_source_chunk_id'), 'risk_signals', ['source_chunk_id'], unique=False)
    op.create_index(op.f('ix_risk_signals_source_clause_id'), 'risk_signals', ['source_clause_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risk_signals_source_clause_id'), table_name='risk_signals')
    op.drop_index(op.f('ix_risk_signals_source_chunk_id'), table_name='risk_signals')
    op.drop_index(op.f('ix_risk_signals_severity'), table_name='risk_signals')
    op.drop_index(op.f('ix_risk_signals_rule_id'), table_name='risk_signals')
    op.drop_index(op.f('ix_risk_signals_contract_id'), table_name='risk_signals')
    op.drop_index(op.f('ix_risk_signals_category'), table_name='risk_signals')
    op.drop_table('risk_signals')
    op.drop_index(op.f('ix_obligations_status'), table_name='obligations')
    op.drop_index(op.f('ix_obligations_source_clause_id'), table_name='obligations')
    op.drop_index(op.f('ix_obligations_source_chunk_id'), table_name='obligations')
    op.drop_index(op.f('ix_obligations_priority'), table_name='obligations')
    op.drop_index(op.f('ix_obligations_due_date'), table_name='obligations')
    op.drop_index(op.f('ix_obligations_contract_id'), table_name='obligations')
    op.drop_table('obligations')
    op.drop_index(op.f('ix_clauses_source_chunk_id'), table_name='clauses')
    op.drop_index(op.f('ix_clauses_contract_id'), table_name='clauses')
    op.drop_index(op.f('ix_clauses_clause_type'), table_name='clauses')
    op.drop_table('clauses')
    op.drop_index(op.f('ix_document_chunks_contract_id'), table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_audit_events_user_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_event_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_entity_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_created_at'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_contract_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_contracts_vendor'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_uploaded_by'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_status'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_risk_level'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_processing_status'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_expiry_date'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_contract_type'), table_name='contracts')
    op.drop_table('contracts')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
