"""
ContractIQ — Schemas Package
"""

from app.schemas.health import DatabaseHealthSchema, HealthResponseSchema
from app.schemas.contract import (
    ContractBase,
    ContractCreate,
    ContractUpdate,
    ContractResponse,
    ContractListResponse,
    ContractUploadResponse,
    ProcessingStatus,
    ContractProcessingStatusUpdate,
    ContractProcessingStatusResponse,
)

from app.schemas.extraction import (
    PageBlock,
    PageExtraction,
    ExtractionResult,
    ContractExtractionResponse,
)

from app.schemas.chunk import (
    ChunkBase,
    ChunkCreate,
    ChunkResponse,
    ContractChunkingResponse,
    ContractChunkListResponse,
    DocumentChunkSummary,
)

from app.schemas.embedding import (
    ContractEmbedRequest,
    ContractEmbeddingResponse,
)

from app.schemas.query import (
    ContractQueryRequest,
    ChunkMatch,
    ContractQueryResponse,
    ContractKeywordQueryRequest,
    KeywordChunkMatch,
    ContractKeywordQueryResponse,
    ContractHybridQueryRequest,
    HybridChunkMatch,
    ContractHybridQueryResponse,
)

from app.schemas.clause import (
    ClauseType,
    ExtractedClauseLLM,
    ChunkClauseExtractionResult,
    ClauseBase,
    ClauseResponse,
    ContractClauseExtractionRequest,
    ContractClauseExtractionResponse,
    ContractClauseListResponse,
)

from app.schemas.obligation import (
    ObligationType,
    ExtractedObligationLLM,
    ClauseObligationExtractionResult,
    ObligationBase,
    ObligationResponse,
    ContractObligationExtractionRequest,
    ContractObligationExtractionResponse,
    ContractObligationListResponse,
)

from app.schemas.contract_fact import (
    FactKey,
    ExtractedFactLLM,
    ClauseFactExtractionResult,
    ContractFactBase,
    ContractFactResponse,
    ContractFactExtractionRequest,
    ContractFactExtractionResponse,
    ContractFactListResponse,
)

from app.schemas.evidence import (
    EvidenceSourceItemType,
    EvidenceBase,
    EvidenceCreate,
    EvidenceResponse,
    EvidenceLineage,
    EvidenceListResponse,
    EvidenceLineageListResponse,
    EvidenceValidationIssue,
    SingleEvidenceValidationResult,
    EvidenceValidationSummary,
)

from app.schemas.risk import (
    RiskSeverity,
    RiskCategory,
    RiskSignalBase,
    RiskSignalResponse,
    RiskEvaluationRequest,
    RiskEvaluationResponse,
    RiskSignalListResponse,
)

from app.schemas.rag import (
    RAGStatus,
    CitationVerificationStatus,
    RAGQueryRequest,
    RAGCitation,
    AnswerClaim,
    LLMCitationItem,
    LLMClaimItem,
    StructuredRAGAnswerLLM,
    RAGQueryResponse,
)

from app.schemas.analyst import (
    AnalystQueryScope,
    ChunkDebugInfo,
    RetrievalDebugInfo,
    AnalystEvidenceCitation,
    AnalystAnswerClaim,
    SingleContractAnalystRequest,
    CrossContractAnalystRequest,
    AnalystQueryResponse,
)

from app.schemas.comparison import (
    DifferenceType,
    DifferenceSeverity,
    ComparisonEvidenceCitation,
    ComparedContractValue,
    DeterministicFieldDifference,
    FieldComparisonRow,
    ObligationComparisonItem,
    ContractComparisonRequest,
    ContractMetadataHeader,
    ContractComparisonResponse,
)

from app.schemas.obligation_api import (
    ObligationEvidenceCitation,
    ObligationDerivedAnalysis,
    ObligationDetailResponse,
    ObligationAnalysisSummary,
    ObligationQueryRequest,
    ObligationQueryResponse,
)

__all__ = [
    "DatabaseHealthSchema",
    "HealthResponseSchema",
    "ContractBase",
    "ContractCreate",
    "ContractUpdate",
    "ContractResponse",
    "ContractListResponse",
    "ContractUploadResponse",
    "ProcessingStatus",
    "ContractProcessingStatusUpdate",
    "ContractProcessingStatusResponse",
    "PageBlock",
    "PageExtraction",
    "ExtractionResult",
    "ContractExtractionResponse",
    "ChunkBase",
    "ChunkCreate",
    "ChunkResponse",
    "ContractChunkingResponse",
    "ContractChunkListResponse",
    "DocumentChunkSummary",
    "ContractEmbedRequest",
    "ContractEmbeddingResponse",
    "ContractQueryRequest",
    "ChunkMatch",
    "ContractQueryResponse",
    "ContractKeywordQueryRequest",
    "KeywordChunkMatch",
    "ContractKeywordQueryResponse",
    "ContractHybridQueryRequest",
    "HybridChunkMatch",
    "ContractHybridQueryResponse",
    "ClauseType",
    "ExtractedClauseLLM",
    "ChunkClauseExtractionResult",
    "ClauseBase",
    "ClauseResponse",
    "ContractClauseExtractionRequest",
    "ContractClauseExtractionResponse",
    "ContractClauseListResponse",
    "ObligationType",
    "ExtractedObligationLLM",
    "ClauseObligationExtractionResult",
    "ObligationBase",
    "ObligationResponse",
    "ContractObligationExtractionRequest",
    "ContractObligationExtractionResponse",
    "ContractObligationListResponse",
    "FactKey",
    "ExtractedFactLLM",
    "ClauseFactExtractionResult",
    "ContractFactBase",
    "ContractFactResponse",
    "ContractFactExtractionRequest",
    "ContractFactExtractionResponse",
    "ContractFactListResponse",
    "EvidenceSourceItemType",
    "EvidenceBase",
    "EvidenceCreate",
    "EvidenceResponse",
    "EvidenceLineage",
    "EvidenceListResponse",
    "EvidenceLineageListResponse",
    "EvidenceValidationIssue",
    "SingleEvidenceValidationResult",
    "EvidenceValidationSummary",
    "RiskSeverity",
    "RiskCategory",
    "RiskSignalBase",
    "RiskSignalResponse",
    "RiskEvaluationRequest",
    "RiskEvaluationResponse",
    "RiskSignalListResponse",
    "RAGStatus",
    "CitationVerificationStatus",
    "RAGQueryRequest",
    "RAGCitation",
    "AnswerClaim",
    "LLMCitationItem",
    "LLMClaimItem",
    "StructuredRAGAnswerLLM",
    "RAGQueryResponse",
    "AnalystQueryScope",
    "ChunkDebugInfo",
    "RetrievalDebugInfo",
    "AnalystEvidenceCitation",
    "AnalystAnswerClaim",
    "SingleContractAnalystRequest",
    "CrossContractAnalystRequest",
    "AnalystQueryResponse",
    "DifferenceType",
    "DifferenceSeverity",
    "ComparisonEvidenceCitation",
    "ComparedContractValue",
    "DeterministicFieldDifference",
    "FieldComparisonRow",
    "ObligationComparisonItem",
    "ContractComparisonRequest",
    "ContractMetadataHeader",
    "ContractComparisonResponse",
    "ObligationEvidenceCitation",
    "ObligationDerivedAnalysis",
    "ObligationDetailResponse",
    "ObligationAnalysisSummary",
    "ObligationQueryRequest",
    "ObligationQueryResponse",
]
